language: python
python:
  - "3.6"
cache: pip
install: 
  - echo "Started"
script: 
  - echo "Running successfully"
deploy:
  provider: elasticbeanstalk
  script:
  - pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  skip_cleanup: true
  access_key_id: 
    secure: "$ACCESS_ID"
  secret_access_key:
    secure: "$SECRET_KEY"
  region: "us-east-2"  
  app: "flask_new"
  env: "FlaskNew-env"
  bucket_name: "elasticbeanstalk-us-east-2-458375213711"
