# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mwkUuquCKEMZ3pzyZ09xrKdvPrpS81eV
"""

# Import necessary packages
import numpy as np
"""
import torch
import torch.nn as nn
import os
import copy
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F
from pytorch_pretrained_bert import BertTokenizer, BertModel, BertConfig
"""
import boto3

from flask import Flask, request, jsonify
import json



# Create a S3 client
client = boto3.client('s3')

BUCKET_NAME = 's3-bucket-new-boto3-aws'

FILE_PATH = 'word.txt'

client.download_file(BUCKET_NAME, FILE_PATH, FILE_PATH)

with open(FILE_PATH, 'r') as w:
    m = w.readlines()
    
m_dict = {"Content String": m}

application = Flask(__name__)

@application.route('/', methods=['GET', 'POST'])
def nlp():
    if request.method == 'GET':
        return jsonify(m_dict)
        #return {'Message': 'Successfully Deployed. Ready for serving'}
"""  
    if request.method == 'POST':
    #temp = False
        string_data = json.loads(request.data)
        string = string_data['input_string']
        #output = {"Mess": string}
        #return jsonify(output)
        result = infer(string)
        if result:
            output = {'Text Review': 'Positive'}
        else:
            output = {'Text Review': 'Negative'}
 """   
        

if __name__ == '__main__':
    application.run(debug=True)